file:
  /var/wazuh-manager/bin/wazuh-control:
    exists: true
    mode: "0750"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/wazuh-manager/etc/wazuh-manager.conf:
    exists: true
    mode: "0660"
    owner: root
    group: wazuh-manager
    filetype: file
    contains: []
  /var/wazuh-manager/etc/sslmanager.cert:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/wazuh-manager/etc/sslmanager.key:
    exists: true
    mode: "0600"
    owner: root
    group: root
    filetype: file
    contains: []
user:
  wazuh-manager:
    exists: true
    groups:
    - wazuh-manager
    home: /var/wazuh-manager
    shell: /sbin/nologin
group:
  wazuh-manager:
    exists: true