file:
  /var/ossec/bin/wazuh-control:
    exists: true
    mode: "0750"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/ossec/etc/lists/audit-keys:
    exists: true
    mode: "0660"
    owner: wazuh
    group: wazuh
    filetype: file
    contains: []
  /var/ossec/etc/ossec.conf:
    exists: true
    mode: "0660"
    owner: root
    group: wazuh
    filetype: file
    contains: []
  /var/ossec/etc/rules/local_rules.xml:
    exists: true
    mode: "0660"
    owner: wazuh
    group: wazuh
    filetype: file
    contains: []
  /var/ossec/etc/sslmanager.cert:
    exists: true
    mode: "0600"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/ossec/etc/sslmanager.key:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
    contains: []
package:
  wazuh-manager:
    installed: true
    versions:
    - 5.0.0
user:
  wazuh:
    exists: true
    groups:
    - wazuh
    home: /var/ossec
    shell: /sbin/nologin
group:
  wazuh:
    exists: true