file:
  /etc/filebeat/filebeat.yml:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/ossec/bin/wazuh-control:
    exists: true
    mode: "0750"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/ossec/etc/lists/audit-keys:
    exists: true
    mode: "0660"
    owner: ossec
    group: ossec
    filetype: file
    contains: []
  /var/ossec/etc/ossec.conf:
    exists: true
    mode: "0660"
    owner: root
    group: ossec
    filetype: file
    contains: []
  /var/ossec/etc/rules/local_rules.xml:
    exists: true
    mode: "0660"
    owner: ossec
    group: ossec
    filetype: file
    contains: []
  /var/ossec/etc/sslmanager.cert:
    exists: true
    mode: "0640"
    owner: root
    group: root
    filetype: file
    contains: []
  /var/ossec/etc/sslmanager.key:
    exists: true
    mode: "0640"
    owner: root
    group: root
    filetype: file
    contains: []
package:
  filebeat:
    installed: true
    versions:
    - 7.10.2
  wazuh-manager:
    installed: true
    versions:
    - 4.2.5
port:
  tcp:1514:
    listening: true
    ip:
    - 0.0.0.0
  tcp:1515:
    listening: true
    ip:
    - 0.0.0.0
  tcp:55000:
    listening: true
    ip:
    - 0.0.0.0
user:
  ossec:
    exists: true
    groups:
    - ossec
    home: /var/ossec
    shell: /sbin/nologin
  ossecm:
    exists: true
    groups:
    - ossec
    home: /var/ossec
    shell: /sbin/nologin
  ossecr:
    exists: true
    groups:
    - ossec
    home: /var/ossec
    shell: /sbin/nologin
group:
  ossec:
    exists: true
process:
  filebeat:
    running: true
  wazuh-analysisd:
    running: true
  wazuh-authd:
    running: true
  wazuh-execd:
    running: true
  wazuh-monitord:
    running: true
  wazuh-remoted:
    running: true
  wazuh-syscheckd:
    running: true
  s6-supervise:
    running: true
  wazuh-db:
    running: true
  wazuh-modulesd:
    running: true
