# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
  wazuh.agent:
    image: wazuh/wazuh-agent:5.0.1
    restart: always
    environment:
      - WAZUH_ENROLLMENT_TOKEN=<TOKEN MINTED BY THE MANAGER>
      #- WAZUH_AGENT_NAME=<WAZUH_AGENT_NAME>
    volumes:
      - wazuh_agent_etc:/var/ossec/etc
volumes:
  wazuh_agent_etc:
