# Certificates for Wazuh multi-node PoC
# Output directory mapped to ./config/wazuh_indexer_ssl_certs
nodes:
  # Indexer nodes
  - name: wazuh1.indexer
    ip:
      - 127.0.0.1
    roles:
      - indexer
  - name: wazuh2.indexer
    ip:
      - 127.0.0.1
    roles:
      - indexer
  - name: wazuh3.indexer
    ip:
      - 127.0.0.1
    roles:
      - indexer
  # Dashboard
  - name: wazuh.dashboard
    ip:
      - 127.0.0.1
    roles:
      - dashboard
  # Manager nodes (filebeat certs)
  - name: wazuh.master
    ip:
      - 127.0.0.1
    roles:
      - manager
  - name: wazuh.worker
    ip:
      - 127.0.0.1
    roles:
      - manager
