# Wazuh Docker Copyright (C) 2021 Wazuh Inc. (License GPLv2)
FROM centos:8

ARG WAZUH_VERSION=4.3.0-1

USER root

# Update and install dependecies
RUN yum install initscripts -y

#Download and install Wazuh indexer
RUN curl https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/yum/wazuh-indexer-${WAZUH_VERSION}.x86_64.rpm --output wazuh-indexer-${WAZUH_VERSION}.x86_64.rpm && \
    rpm -i wazuh-indexer-${WAZUH_VERSION}.x86_64.rpm && \
    yum clean all && rm -rf /var/cache/yum && rm -rf wazuh-indexer-${WAZUH_VERSION}.x86_64.rpm

COPY config/entrypoint.sh /

RUN chmod 700 /entrypoint.sh

# Services ports
EXPOSE 9700

ENTRYPOINT [ "/entrypoint.sh" ]